### ISSUE TITLE
Failure to compile due to package

### ISSUE THREAD

**Issue by martintc** [FreakHaxme/Game-tracker#5]
For some reason with the change of package name, it does not seem to compile on my end.

``todd@localhost:~/Testing/GameTracker> javac Main.java 
Main.java:1: error: package initiativeDnD does not exist
import initiativeDnD.DnD;
                    ^
Main.java:82: error: cannot find symbol
                                DnD.run();
                                ^
  symbol:   variable DnD
  location: class Main.EventHandler
2 errors``

**Comment by FreakHaxme** [comment]
That's very odd. Do you need to rename a folder or something? It compiles on my end.

**Comment by martintc** [comment]
I got it to compile so you can close this, no issue. Just so etching weird that happened on my netbook.
